export const FETCH_ARTICLES_REQUESTS = 'FETCH_ARTICLES_REQUESTS';
export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS';
export const FETCH_ARTICLES_ERROR = 'FETCH_ARTICLES_ERROR';
export const FETCH_ARTICLES_BY_ID_REQUESTS = 'FETCH_ARTICLES_BY_ID_REQUESTS';
export const FETCH_ARTICLES_BY_ID_SUCCESS = 'FETCH_ARTICLES_BY_ID_SUCCESS';
export const FETCH_ARTICLES_BY_ID_ERROR = 'FETCH_ARTICLES_BY_ID_ERROR';
export const FETCH_COMMENTS_BY_ARTICLE_ID_REQUESTS = 'FETCH_COMMENTS_BY_ARTICLE_ID_REQUESTS';
export const FETCH_COMMENTS_BY_ARTICLE_ID_SUCCESS = 'FETCH_COMMENTS_BY_ARTICLE_ID_SUCCESS';
export const FETCH_COMMENTS_BY_ARTICLE_ID_ERROR = 'FETCH_COMMENTS_BY_ARTICLE_ID_ERROR';
export const ADD_COMMENTS_BY_ARTICLE_ID_POST = 'ADD_COMMENTS_BY_ARTICLE_ID_POST';
export const ADD_COMMENTS_BY_ARTICLE_ID_SUCCESS = 'ADD_COMMENTS_BY_ARTICLE_ID_SUCCESS';
export const ADD_COMMENTS_BY_ARTICLE_ID_ERROR = 'ADD_COMMENTS_BY_ARTICLE_ID_ERROR';

// articleVoteUp
export const ARTICLE_VOTE_UP_REQUEST = 'ARTICLE_VOTE_UP_REQUEST';
export const ARTICLE_VOTE_UP_SUCCESS = 'ARTICLE_VOTE_UP_SUCCESS';
export const ARTICLE_VOTE_UP_ERROR = 'ARTICLE_VOTE_UP_ERROR';

// articleVoteDown
export const ARTICLE_VOTE_DOWN_REQUEST = 'ARTICLE_VOTE_DOWN_REQUEST';
export const ARTICLE_VOTE_DOWN_SUCCESS = 'ARTICLE_VOTE_DOWN_SUCCESS';
export const ARTICLE_VOTE_DOWN_ERROR = 'ARTICLE_VOTE_DOWN_ERROR'; 